### ISSUE TITLE
AFC unable to manage files

### ISSUE THREAD

**Issue by Spidy123222** [SideStore/SideStore#156]
AFC unable to manage files seems to be a common error message. Not quite sure why it happens but seems random which requires a app or idevice restart.

**Comment by jkcoxson** [comment]
None of us know why without logs either.

**Comment by Spidy123222** [comment]
There was no useful info with the logs whenever I tried. You would just get same message. I'll try sending it anyways which I have to re-make.

**Comment by Spidy123222** [comment]
> If you can provide more information on how to reproduce this issue, I can begin to investigate. Otherwise, I don't know where to start

There is no reliable way to reproduce the issue other than use sidestore until it happens.

**Comment by mmmago** [comment]
Same error here.

**Comment by Starli0n** [comment]
I have the same issue and the log can be found at #515.

I reset the paring file but it did not work.
I reset the adi.db, 2FA login again, it did not work either.
I even reinstalled SideStore from scratch using SideServer method + custom anisette server v3

To give more context, I manage in running some apps at a point.
But the issue appears when I tried to unload an app.

**Comment by daisuru** [comment]
for me its happening when im trying to install pojav launcher. its frustrating bc this is the only program i've found that even got me close to getting mc java on my ipad.

**Comment by Spidy123222** [comment]
Installing via altserver seems to help most people's problems from what I saw in discord. Could likely try that.

**Comment by hckrpr** [comment]
It also happens to me when i try to install an app using sidestore. The app was injected with deb using sideloadly (i deselect cydia) and im installing it using vpn whilst also plugging it into the sideserver (it wont work without the vpn for some reason)

**Comment by Weekly-Tech-Tips** [comment]
I'm having the same error

**Comment by natejgallagher** [comment]
Any advancements or new knowledge on the topic? I've tinkered quite a bit and this error seems equivalent to the blue screen of death.

**Comment by airjer** [comment]
Same issue here following all the suggestions...

**Comment by christorrella** [comment]
> Same issue here I redid everything like 3 times and it corrected iteself. I think admin mode on the config generation "may" have been what fixed it, no clue.

I just generated the jitterbog pairing file with sudo and that fixed it for me! Can confirm.

**Comment by herobrine8763** [comment]
> I just generated the jitterbug pairing file with `sudo` and that fixed it for me! Can confirm.

Does 'sudo' mean running it as administrator?

**Comment by junepark678** [comment]
invalid pairing usually

**Comment by checkso** [comment]
> > Same issue here I redid everything like 3 times and it corrected iteself. I think admin mode on the config generation "may" have been what fixed it, no clue.
> 
> I just generated the jitterbug pairing file with `sudo` and that fixed it for me! Can confirm.

This was the solution also for me. Should be added to the documentation.

**Comment by derpbyte** [comment]
I had this problem when downloading an IPA and clicking share > SideStore on iOS 18. I fixed it by turning on the WireGuard VPN.

**Comment by sabbiosas** [comment]
I have the same problem and i read the comment but how do i generate jitterbug with 'sudo'
What does it mean? Sorry im new

**Comment by neoarz** [comment]
> I have the same problem and i read the comment but how do i generate jitterbug with 'sudo' What does it mean? Sorry im new

you dont need to generate jitterbug with sudo, im guessing your on a mac, you just double click on the jitterbug application and it should open a terminal window

**Comment by sabbiosas** [comment]
Im using a window pc and an iphone, i used the jitterbug file that was on the tutorial of sidestore . 4 days ago i had this issue and tried to refresh the pairing file but the problem does not resolve

**Comment by sabbiosas** [comment]
> > I have the same problem and i read the comment but how do i generate jitterbug with 'sudo' What does it mean? Sorry im new
> 
> you dont need to generate jitterbug with sudo, im guessing your on a mac, you just double click on the jitterbug application and it should open a terminal window

Im using a window pc and an iphone, i used the jitterbug file that was on the tutorial of sidestore . 4 days ago i had this issue and tried to refresh the pairing file but the problem does not resolve

**Comment by funschoolwork** [comment]
i know im late but its because you need a passcode on your device while generating your pairing file

**Comment by christorrella** [comment]
I have one, this isn’t the issue

**Comment by Bennebotix** [comment]
I am having the same issue, is there any solution?

**Comment by officiallor** [comment]
> I am having the same issue, is there any solution?

connect on stosvpn and retry

**Comment by LostShadowGD** [comment]
What usually works for me:

1. Check StosVPN is on. Whenever you turn WiFi off, StosVPN turns off too. If that doesn't work,
2. Regenarate pairing file. If that doesn't work,
3. Reboot iDevice. If that doesn't work,
4. Do steps 1-3 for 45 freaking minutes until it works

**Comment by CelloSerenity** [comment]
> What usually works for me:
> 
> 1. Check StosVPN is on. Whenever you turn WiFi off, StosVPN turns off too. If that doesn't work,
> 2. Regenarate pairing file. If that doesn't work,
> 3. Reboot iDevice. If that doesn't work,
> 4. Do steps 1-3 for 45 freaking minutes until it works

Correction: StosVPN stays on even when WiFi or cellular is off, that's one of the main reasons it was created. If you are experiencing this behavior please make a bug reports with logs, a screen recording, or something similar
