### ISSUE TITLE
[BUG] 0.5.8 Constantly crashes on iOS 18 and Wi-Fi or Wireguard not connected

### ISSUE THREAD

**Issue by gamefreak89** [SideStore/SideStore#702]
### Describe the bug

The bug constantly crashes sidestore after refresh on every time I hit the refresh button, or the green button, or even exiting out, and loading it back up. This goes for the app list as well. As for Wi-fi or Wireguard not connected bug, this is happening with the latest release of 0.5.8 sidestore. Plus, I reset it's pairing file, and re-added it to make sure that it worked properly, along with removing it's profile from VPN and Profile management from within the settings menu, and re-adding it, after installation of sidestore. This at first worked, but after trying to resfresh and/or import an ipa file, I'm met with either a crash or the Wi-fi bug.  

This also goes for trying to tap on the home screen of side store or within the apps menu, as well. I already went through the installation process of reinstalling sidestore through altserver, and removing it's profile from Device & VPN Management. It only works for the first few tries, until the bug kicks in. Not to mention, I even tried to rename pairing file to "ALTPairingFile", and I encountered the same bug. 

### Instructions to reproduce

1. Go to Sidestore.io 
2. Follow the onscreen instructions to install Altserver, along with jitterbug and sidestore.
3. Install Wireguard and share the sidestore config file with wireguard.
4. Go to Settings> General> VPN & Device Management, and install it's profile.
5. Go back to Sidestore, and pair it's pairing file.
6. Reload sidestore, and hit either the green button or Refresh all.
7. After that, go to my apps, and import an ipa file.
8. After an ipa file is imported and signed/installed. Exit of out of Sidestore
9. Load up sidestore again. Then try hitting the refresh button or any of the green buttons, only to be met with the Wi-fi or Wireguard is not connected bug, 
10. Click the + icon to import a ipa file, only to be met with the Wi-fi or Wireguard is not connected bug. 
11. Exit out of Sidestore, go to wireguard, tap on sidestore and re-tap it to reconnect.
12. Go back to sidestore and try to import or refresh apps only to be met with the Wi-fi or Wireguard is not connected bug. 
13. Exit of out sidestore and go back to it, go to settings, go to reset pairing file.
14. Reload sidetore and load it's pairing file.
15. After reloading it's pairing file, sidestore should work fine for the first one or two tries after refreshing it or importing an ipa file.
16. After a successful attempt of importing an ipa file and hitting the refresh button, exit out of sidestore.
17. Load sidestore back up, tap on Refresh all or click on any of the green buttons listed in my apps and sidestore crashes.
18. Exit ouf of sidestore and remove it's icon from the home screen.
19. Go to my apps and tap on sidestore.
20. Sidestore crashes everytime on either the home screen or either in my apps. 

### What version of SideStore are you using?

0.5.8

### Other info

I tried to list as much consistent step by step instructions on how to reproduces the bug. I'm using an iPhone 13 Pro max on iOS 18 Public. Sidestore was working fine yesterday, when I first installed it through altsever, but it crashed on me the first go round. Then I uninstalled it, went through the same process 3 times of installation, and renamed the pairing file to "ALTPairingFile", and paired it after sidestore gave me the wi-fi bug, and still refused to refresh/import and ipa file. So I uninstalled it again, uninstalled wireguard, reinstalled sidestore through altserver, doube-clicked on jitterbug and zipped it to my ios device, uncompressed it, then paired it as is to sidestore, then re-downloaded wireguard, shared the config file wireguard, then went back to sidestore, everything is working fine, imported an ipa file, hit the refresh button everything is good to go.

After that, I checked to make sure wireguard is still connected (Which it is), then I loaded back up sidestore, hit both either the refresh button or the import button under my apps, I encounter the No Wi-FI or Wireguard is connected bug, I exit out of Sidestore. I restart my iphone, start my iphone, start up wireguard, and reconnect sidetore, load up sidestore and spam press the refresh button or import button under my apps. It would work for the first few tries, then it would throw me that bug every single time. 

The last resort is redoing everything from scratch. By uninstalling sidestore again and any connected apps to it. Following the instructions given to me, then when everything is setup, load up sidestore, import and an ipa file, and hit the refresh button. After that it works for the first time, but going forward exiting out of sidestore and loading, trying to load it back up will result in a constant crash with no errors thrown my way. 
![IMG_2003](https://github.com/user-attachments/assets/29b052ec-74fa-4d0c-b38b-ad227ca4c89f)

https://github.com/user-attachments/assets/03052414-840e-47a0-a200-5669cd64099e

**Comment by yodaluca23** [comment]
I don't know if this is related, but whenever I first updated to iOS 18 and refreshed all my apps in SideStore they all refreshed except one of my sideloaded apps, and then SideStore closed as it usually does to refresh itself, but then it never started like the installation Progress bar thing I gave it a couple minutes and Nothing I tried opening it and it would just crash immediately. I gave it a couple days and it just started working and since then it's worked fine...

**Comment by skyerday** [comment]
I also encountered this issue. After updating SideStore by itself, I was unable to open it again. I connected to Xcode to check the logs and found a crash report:

`ASI found [dyld] (sensitive) 'Library not loaded: @rpath/Roxas.framework/Roxas
  Referenced from: <6840AE1B-3E68-3D9E-A973-07545083660C> /private/var/containers/Bundle/Application/6DB334E6-6402-4F91-85E3-64605587B36B/App.app/SideStore
  Reason: tried: '/usr/lib/swift/Roxas.framework/Roxas' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/Roxas.framework/Roxas' (no such file), '/private/var/containers/Bundle/Application/6DB334E6-6402-4F91-85E3-64605587B36B/App.app/Frameworks/Roxas.framework/Roxas' (code signature invalid in <2B726600-8713-37B9-A482-471D1EDF0A3D> '/private/var/containers/Bundle/Application/6DB334E6-6402-4F91-85E3-64605587B36B/App.app/Frameworks/Roxas.framework/Roxas' (errno=85) sliceOffset=0x00000000, codeBlobOffset=0x0005E1D0, codeBlobSize=0x000049D0), '/usr/lib/swift/Roxas.framework/Roxas' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/Roxas.framework/Roxas' (no such file), '/private/var/containers/Bundle/Application/6DB334<…>'`

**Comment by abjugard** [comment]
I had this issue, I don't know if I identified the actual problem, but I managed to solve it by generating a new pairing file.

My guess is that after enabling `Developer mode` the pairing file generated before that stopped working, but was still a valid file that SideStore accepted.

On top of that issue I ran into one more issue, when I re-signed the SideStore installation that came from AltServer, SideStore would stop working, it would just crash when opening.

Fixed that issue by using the initially AltServer-installed version of SideStore to install a new copy of the SideStore IPA.

After this everything is working correctly for me!

**Comment by polymo1** [comment]
> My guess is that after activating `Developer mode` the pairing file which I had generated before that stopped working, but was still a valid file that SideStore accepted.

It is possible that your pairing file expired, but I would like to note that SideStore currently has no way to detect if a pairing file is still good or not. We have some ideas as to how we would like to tackle this problem, but it isn't currently planned.

As for the Roxas error, it's definitely something I've not seen before. If your SideStore breaks, you must reinstall it with AltServer. It is important that you are refreshing immediately after installation, and that you are not letting SideStore expire. 

For right now I'm going to close this issue as not planned, since both scenarios mentioned in the original post are known issues. Thank you for your report.

**Comment by madebycm** [comment]
> I had this issue, I don't know if I identified the actual problem, but I managed to solve it by generating a new pairing file.
> 
> My guess is that after activating `Developer mode` the pairing file which I had generated before that stopped working, but was still a valid file that SideStore accepted.
> 
> On top of that issue I ran into one more issue, when I re-signed the SideStore installation that came from AltServer, SideStore would stop working, it would just crash when opening.
> 
> Fixed that issue by using the initially AltServer-installed version of SideStore to install a new copy of the SideStore IPA.
> 
> After this everything is working correctly for me!

Using the initially AltServer-installed version of SideStore to install SideStore again fixes everything. Black magic. Thanks!

**Comment by abjugard** [comment]
> It is possible that your pairing file expired, but I would like to note that SideStore currently has no way to detect if a pairing file is still good or not. We have some ideas as to how we would like to tackle this problem, but it isn't currently planned.

Doubtful, this is a pairing file I generated literal minutes before launching SideStore, for my brand new 16P. The order was something like this:

1. Connect phone
2. Approve connection
3. Use AltServer to install SideStore058.ipa
4. Generate pairing file
5. Fail to start SideStore as `Developer mode` was not enabled
6. Activate `Developer mode`
7. Launch SideStore
8. Observe the "Wi-Fi or Wireguard not connected" message
9. Waste a bunch of time fucking about with settings having no effect
10. Generate new pairing file
11. Boom works
12. Refresh AltServer-installed SideStore058.ipa
13. SideStore won't launch - lose hope again
14. Re-install SideStore058.ipa using AltServer
15. Use SideStore to sideload SideStore058.ipa from the phone
16. Happy days

> Using the initially AltServer-installed version of SideStore to install SideStore again fixes everything. Black magic. Thanks!

Happy to help! I was mega frustrated and worried I would be locked out of Apollo and forced to launch and use Reddit.app instead for any amount of time, which I believe was actually retroactively added to the Geneva Convention as a war crime.

**Comment by gamefreak89** [comment]
I tried those steps, even sharing the sidestore ipa file to itself, reset the pairing file and pairing it again, then reinstalling altserver on my macbook and iphone. I'm still encountering the same issue.

**Comment by ddriver88** [comment]
Chiming in here as someone also experiencing this issue. iPhone 16 Pro Max, iOS 18.1

Sidestore launches initially and I’m able to install the desired ipa. It only occurs when I click to Refresh. Sidestore closes as expected, then continually crashes upon launch thereafter.

**Comment by skyerday** [comment]
Same here. 
macOS Sequioa with iOS 18

* Uninstall SideStore
* pairing with jitterbugpair
* install SideStore from AltServer
* Launch SideStore and refresh SideStore immediately

After that, SideStore always crash in launching.

I will try do it in Windows sometime to check pairing issue.

**Comment by meshuggah44** [comment]
> Same here. macOS Sequioa with iOS 18
> 
> * Uninstall SideStore
> * pairing with jitterbugpair
> * install SideStore from AltServer
> * Launch SideStore and refresh SideStore immediately
> 
> After that, SideStore always crash in launching.
> 
> I will try do it in Windows sometime to check pairing issue.

Having the exact same issue on Sequoia and iOS 18

**Comment by skyerday** [comment]
I try same steps in Windows, works OK!

I only met no wifi/no vpn issue, I try kill app and relaunch, will ok sometimes.

**Comment by moogstain** [comment]
> Fixed that issue by using the initially AltServer-installed version of SideStore to install a new copy of the SideStore IPA.

you are a saint for this

**Comment by abjugard** [comment]
@meshuggah44 @ddriver88 - after the first launch, are you sure you're _installing_ the SideStore IPA from SideStore instead of refreshing? If you use AltServer to install, and then refresh without re-installing, it seems to break the installation, I guess AltServer changes something that causes this.

@gamefreak89 - did you _generate a new pairing file_ after enabling `Developer mode`? Simply resetting the pairing file and using the same pairing file again will have no effect, it seems you need to use `jitterbugpair` _again_ after enabling `Developer mode`, and then use this new pairing going forwards.

**Comment by meshuggah44** [comment]
@abjugard sorry, I had missed the step in which I should've reinstalled the SideStore using the original .ipa within SideStore itself. I just did that and I'm not having the post-refresh crash anymore

**Comment by iainnn** [comment]
> @meshuggah44 @ddriver88 - after the first launch, are you sure you're _installing_ the SideStore IPA from SideStore instead of _refreshing_? If you use AltServer to install, and then refresh without re-installing, it seems to break the installation, I guess AltServer changes something that causes this. Just have SideStore _install itself_ using the same IPA you installed via AltServer, and it should start working correctly.
> 
> 
> 
> @gamefreak89 - did you _generate a new pairing file_ after enabling `Developer mode`? Simply resetting the pairing file and using the same pairing file again will have no effect, it seems you need to use `jitterbugpair` _again_ after enabling `Developer mode`, and then use this new pairing going forwards.

so every time i want to refresh sidestore i should do it through this method or after side loading the ipa in sidestore i can refresh normally whenever?

**Comment by meshuggah44** [comment]
> > @meshuggah44 @ddriver88 - after the first launch, are you sure you're _installing_ the SideStore IPA from SideStore instead of _refreshing_? If you use AltServer to install, and then refresh without re-installing, it seems to break the installation, I guess AltServer changes something that causes this. Just have SideStore _install itself_ using the same IPA you installed via AltServer, and it should start working correctly.
> > @gamefreak89 - did you _generate a new pairing file_ after enabling `Developer mode`? Simply resetting the pairing file and using the same pairing file again will have no effect, it seems you need to use `jitterbugpair` _again_ after enabling `Developer mode`, and then use this new pairing going forwards.
> 
> so every time i want to refresh sidestore i should do it through this method or after side loading the ipa in sidestore i can refresh normally whenever?

After sideloading the .ipa within SideStore it should be able to refresh itself automatically.

Although in my case I find that it often gets stuck while refreshing and it’ll only work when I press “refresh all”
