### ISSUE TITLE
[BUG] No valid server found

### ISSUE THREAD

**Issue by PhilippGamer007** [SideStore/SideStore#813]
### Describe the bug

Whenever I try to sing in with my apple id sidestore tells me that there are no valid server found

### Instructions to reproduce

When I click on the login button and fill in my passwort the error appears , I already tryed using another version and reinstalling sidestore

### What version of SideStore are you using?

The newest , I just updated

**Comment by iAmANormalUser** [comment]
# Unable to login
# ---------------------------
1. **Fixes**
> -# 1. Switch anisette servers (ex: to Macley). Steps : Open SideStore - Settings - Scroll down to Anisette Servers - click Macley
> -# 2. Reset adi.pb
> -# 3. If prompted to revoke previous certificate, **ALWAYS** click yes.
> -# 4. **Contact helpers for further assistance, or open a post in support forum.**
-# Channels : https://discord.com/channels/949183273383395328/1279548738586673202 , https://discord.com/channels/949183273383395328/1020114888720384032.

**Comment by PhilippGamer007** [comment]
tysm , I worked

**Comment by mahee96** [comment]
fixed in nightly

**Comment by michael1900** [comment]
> fixed in nightly

Hi, in which nightly? 0.5.10 or last 0.6? And in this last 0.6 the script/shortcut to refresh is working? Asking this because last time that i tried the script was not ready if you remember.

**Comment by kevin-rabefaritra** [comment]
> > fixed in nightly
> 
> Hi, in which nightly? 0.5.10 or last 0.6? And in this last 0.6 the script/shortcut to refresh is working? Asking this because last time that i tried the script was not ready if you remember.

`0.6.0-nightly` worked for me.

**Comment by michael1900** [comment]
> > > fixed in nightly
> > 
> > 
> > Hi, in which nightly? 0.5.10 or last 0.6? And in this last 0.6 the script/shortcut to refresh is working? Asking this because last time that i tried the script was not ready if you remember.
> 
> `0.6.0-nightly` worked for me.

I just tried and honestly it seems not fixed. The first login with the Apple ID never works for me with default sidestore server. To the first login i need to use always a different server. Done many tries. 
After the login, then every single refresh always works ALSO with the default sidestore server.
I don't know why for many this is fixed, but for me there is still the problem. Tried with last 0.6 nightly.

**Comment by michael1900** [comment]
> fixed in nightly

Are you sure bro?

**Comment by Whetyn** [comment]
> # Impossibile effettuare l'accesso
> # ---------------------------
> 1. **Correzioni**
> 
> > -# 1. Cambia i server anisette (es: a Macley). Passaggi : Apri SideStore - Impostazioni - Scorri verso il basso fino a Server Anisette - fai clic su Macley -# 2. Reimposta adi.pb -# 3. Se viene richiesto di revocare il certificato precedente, fare **SEMPRE** clic su Sì.  -# 4. **Contatta gli assistenti per ulteriore assistenza o apri un post nel forum di supporto.** -# Canali : https://discord.com/channels/949183273383395328/1279548738586673202 , https://discord.com/channels/949183273383395328/1020114888720384032.

I solved it by doing this (Switch anisette servers (ex: to Macley). Steps : Open SideStore - Settings - Scroll down to Anisette Servers - click Macley) thank you very much

**Comment by Auxority** [comment]
Just had this issue, but the suggested fix works :)
Maybe it could automatically use a fallback server if the first one fails.
